docs: update readme
Open-Attestation/decentralized-renderer-react-components pull request #121
Opened 2023-12-27 03:56 UTC by rollerchloe

## Summary

This readme is updated so that it can be retrieved as a remote file in the documentation website.

## Changes

- Proofread the content 
- Update broken links

2024-02-19 07:33 UTC, yapyuyou requested changes

2024-02-19 07:33 UTC, yapyuyou commented on README.md
> +- `npm run storybook`: to start a storybook, create stories, and visualize the different component
```suggestion
- `npm run storybook`: to start a storybook, create stories, and visualize different components
```

2024-02-19 07:33 UTC, yapyuyou commented on README.md
> +- `npm run example:application`: to run the example build with the library to develop an hosting application.
```suggestion
- `npm run example:application`: to run an example application built with this library. 
```

2024-02-19 07:33 UTC, yapyuyou commented on README.md
> +- `npm run example:renderer`: to run the example build with the library to develop a decentralized renderer.
```suggestion
- `npm run example:renderer`: to run an example decentralized renderer built with this library. 
```

2024-02-19 07:53 UTC, rollerchloe commented on README.md
> +  - `id`: A unique identifier withing the current array of the template
sorry for typo - fixed

2024-02-19 07:53 UTC, rollerchloe commented on README.md
> +  - `label`: A string to represent what the template is
added

2024-02-19 07:54 UTC, rollerchloe commented on README.md
> +- `npm run storybook`: to start a storybook, create stories, and visualize the different component
updated

2024-02-19 07:56 UTC, rollerchloe commented on README.md
> +- `npm run example:application`: to run the example build with the library to develop an hosting application.
updated

2024-02-19 07:57 UTC, rollerchloe commented on README.md
> +- `npm run example:renderer`: to run the example build with the library to develop a decentralized renderer.
updated

2024-02-20 02:22 UTC, yapyuyou approved these changes

2024-02-20 07:17 UTC, merged