fix: e2e
Open-Attestation/decentralized-renderer-react-components pull request #69
Opened 2021-11-10 08:55 UTC by eugbyte

attempt to fix the failing circle ci;. Failure seems to occur at `npm run build:umd step`, so i upgraded browserlist

```
> @govtechsg/decentralized-renderer-react-components@0.0.0-development build:umd
> webpack "--mode" "production"

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
```

2021-11-10 09:36 UTC, ryanseee commented
hmm seems like its still failing. I checked online, people mentioned might be something to do with the node version?

https://stackoverflow.com/questions/69692842/error0308010cdigital-envelope-routinesunsupported

2021-11-10 10:00 UTC, eugbyte commented
https://github.com/webpack/webpack/issues/14532

Seems like when node version is upgrade to 17, `digital envelope routines::unsupported` error occurs with webpack

2021-11-11 01:27 UTC, ryanseee approved these changes
lgtm

2021-11-11 01:35 UTC, Nebulis commented on .circleci/config.yml
> +      - image: 'cimg/node:16.12.0'
use circleci/node:lts

2021-11-11 01:39 UTC, Nebulis requested changes
see comment

2021-11-11 01:55 UTC, Nebulis approved these changes

2021-11-11 01:59 UTC, merged

2021-11-11 02:01 UTC, john-dot-oa commented
:tada: This PR is included in version 3.5.4 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@govtechsg/decentralized-renderer-react-components/v/3.5.4)
- [GitHub release](https://github.com/Open-Attestation/decentralized-renderer-react-components/releases/tag/v3.5.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: